version: "3"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: blockcall_frontend
    env_file:
      - ./env/.env.ui.ts
    environment:
      - NODE_ENV=development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./uploads:/var/storage
    networks:
      - blockcall-network
networks:
  blockcall-network:
    external: true 